import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
// Note: Verify this import matches your actual project structure
import '../../services/api_client.dart';

class FriendsTabScreen extends StatelessWidget {
  const FriendsTabScreen({Key? key}) : super(key: key);

  void _startDM(BuildContext context, String friendId) async {
    try {
      // Call our new backend endpoint to get/create DM
      // Make sure you have a generic post method in your ApiClient
      final response = await ApiClient.getOrCreateDM(friendId);
      final convId = response['conversation_id'];

      if (context.mounted) {
        context.push('/chat/$convId');
      }
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Failed to start chat')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: [
        // ==========================================
        // 1. PENDING REQUESTS SECTION
        // ==========================================
        ListTile(
          leading: CircleAvatar(
            backgroundColor: Colors.blue.shade50,
            child: const Icon(Icons.person_add, color: Colors.blue),
          ),
          title: const Text('Friend Requests',
              style: TextStyle(fontWeight: FontWeight.w500)),
          trailing: Container(
            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
            decoration: BoxDecoration(
              color: Colors.red,
              borderRadius: BorderRadius.circular(10),
            ),
            child: const Text('2',
                style: TextStyle(color: Colors.white, fontSize: 12)),
          ),
          onTap: () {
            // TODO: Navigate to Friend Requests Screen
          },
        ),

        const Divider(),

        // ==========================================
        // 2. ACTIVE FRIENDS LIST HEADER
        // ==========================================
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
          child: Text(
            'ALL FRIENDS',
            style: TextStyle(
                fontSize: 12,
                fontWeight: FontWeight.bold,
                color: Colors.grey.shade600),
          ),
        ),

        // ==========================================
        // 3. MOCK FRIEND ITEM
        // ==========================================
        // In the real app, this will be generated by a ListView.builder
        // fed by a FutureBuilder or Riverpod Provider.
        ListTile(
          leading: const CircleAvatar(
            backgroundImage: NetworkImage('https://i.pravatar.cc/150?img=11'),
          ),
          title: const Text('Rahul Sharma'),
          subtitle: const Text('Online',
              style: TextStyle(color: Colors.green, fontSize: 12)),
          trailing: IconButton(
            icon: const Icon(Icons.chat_bubble_outline),
            color: Colors.blue,
            onPressed: () => _startDM(context, 'mock-uuid-for-rahul'),
          ),
        ),
      ],
    );
  }
}
